Update lodestar creation package script using new official binary executable
A huge thank you to @nflaig from the Lodestar project for his invaluable help and guidance. With their effort and  support, we've successfully updated our lodestar creation package script to utilize the new official binary executable available. This update ensures better performance and compatibility.

Thanks again, @nflaig, for your contributions to the EoA community!

diff --git a/fpm-package-builder/l1-clients/consensus-layer/lodestar/Makefile b/fpm-package-builder/l1-clients/consensus-layer/lodestar/Makefile
--- a/fpm-package-builder/l1-clients/consensus-layer/lodestar/Makefile
+++ b/fpm-package-builder/l1-clients/consensus-layer/lodestar/Makefile
@@ -4,7 +4,7 @@
 SHELL := /bin/bash
 
 LODESTAR_VERSION := $(shell curl -s "https://api.github.com/repos/ChainSafe/lodestar/releases/latest" | jq '.tag_name' | tr -d  '"'| tr -d "v")
-LODESTAR_BIN_PATH := "lodestar.bin" # Update this to the path where your lodestarbin is located
+LODESTAR_URL := $(shell curl -s "https://api.github.com/repos/ChainSafe/lodestar/releases/latest" | jq -r '.assets[] | select(.name | contains("arm64")).browser_download_url')
 
 PKG_RELEASE := 0
 PKG_NAME := lodestar
@@ -35,8 +35,7 @@ FPM_DEB_OPTS := -s dir -n $(PKG_NAME) -v $(LODESTAR_VERSION) --license $(PKG_LIC
 all: prepare deb clean test
 
 prepare: ## Replace Lodestar binary with Lodestar binary
-
-	cp $(LODESTAR_BIN_PATH) $(SOURCESDIR)/usr/bin/lodestar
+	wget $(LODESTAR_URL) -O - | tar -xz -C $(SOURCESDIR)/usr/bin/
 
 deb: ## Create deb package
 	fpm -t deb -p $(PKG_DEB) $(FPM_DEB_OPTS)
@@ -50,12 +49,11 @@ clean: ## Clean up
 
 test:
 	@if [ -f $(OUTPUTDIR)/$(PKG_DEB) ]; then \
-        printf "\033[32mPackage $(PKG_DEB) successfully created\033[0m\n"; \
-    else \
-        printf "\033[31mError: Package $(PKG_DEB) not found\033[0m\n"; \
-        exit 1; \
-    fi
+		printf "\033[32mPackage $(PKG_DEB) successfully created\033[0m\n"; \
+	else \
+		printf "\033[31mError: Package $(PKG_DEB) not found\033[0m\n"; \
+		exit 1; \
+	fi
 
 help:  ## List targets.
 	@echo -e "$$(grep -hE '^\S+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##\s*/:/' -e 's/^\(.\+\):\(.*\)/\\x1b[36m\1\\x1b[m:\2/' | column -c2 -t -s :)"
-
