refactor eoa_send

diff --git a/fpm-package-builder/ethereumonarm-utils/sources/usr/sbin/eoa_send b/fpm-package-builder/ethereumonarm-utils/sources/usr/sbin/eoa_send
--- a/fpm-package-builder/ethereumonarm-utils/sources/usr/sbin/eoa_send
+++ b/fpm-package-builder/ethereumonarm-utils/sources/usr/sbin/eoa_send
@@ -1,5 +1,21 @@
 #!/usr/bin/env bash
 
-eoa_chech=$(which eoa_check)  
- 
-$eoa_chech | sed -E 's/([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3})/XXX.XXX.\3\4/g' | curl -F 'sprunge=<-' http://sprunge.us
+eoa_check=$(which eoa_check)  
+
+if [ -z "$eoa_check" ]; then
+    echo "eoa_check not found"
+    exit 1
+fi
+
+output=$($eoa_check)
+
+# remove all but the last octet of IP addresses
+output=$(echo "$output" | sed -E 's/([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3})/XXX.XXX.\3\4/g')
+
+# check if curl command is available
+if ! [ -x "$(command -v curl)" ]; then
+    echo "curl command not found, please install it"
+    exit 1
+fi
+
+curl --no-progress-meter -d 'sprunge=<-' http://sprunge.us <<< "$output" 
